[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/monitoring/health/latency"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
PORT = "8000"
WORKERS = "2"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
STATIC_DIR = "/app/static"

# Additional Metadata for Railway Dashboard
[metadata]
name = "Telegram Parser API"
description = "FastAPI application for parsing Telegram groups"

# This section defines your main backend application service
[[services]]
name = "backend"
internal_port = 8000
auto_deploy = true
src = "."

# Define the frontend service
[[services]]
name = "frontend"
internal_port = 80
auto_deploy = true
src = "frontend"

# Reference the PostgreSQL plugin
[[plugins]]
name = "postgresql"

# Reference the Redis plugin
[[plugins]]
name = "redis"

# Reference the PostgreSQL variables in your main service
[plugins.var]
# These are used by the postgres plugin
POSTGRES_USER = "postgres"
POSTGRES_DB = "railway"

# Environment variable for the frontend to know where the backend is
[services.frontend.env]
REACT_APP_API_URL = "${RAILWAY_SERVICE_BACKEND_URL}"

# Mount points for static files
[services.backend.mounts]
source = "/app/static"
destination = "/app/static"
