[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
PORT = "8000"
WORKERS = "2"
PYTHONUNBUFFERED = "1"

# Additional Metadata for Railway Dashboard
[metadata]
name = "Telegram Parser API"
description = "FastAPI application for parsing Telegram groups"

# This section defines your main application service
[service]
internal_port = 8000
auto_deploy = true

# Reference the PostgreSQL plugin
[[plugins]]
name = "postgresql"

# Reference the Redis plugin
[[plugins]]
name = "redis"

# Reference the PostgreSQL variables in your main service
[plugins.var]
# These are used by the postgres plugin
POSTGRES_USER = "postgres"
POSTGRES_DB = "railway" # Railway Configuration
