[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[var]
DISABLE_DB = "false"
PORT = "8080"

# Configure database connection - uncomment and adjust as needed
# DATABASE_URL = "${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"

# This section defines your main application service
[service]
internal_port = 8080
auto_deploy = true

# Create and configure a PostgreSQL service
[[plugins]]
type = "postgresql"

# Reference the PostgreSQL variables in your main service
[plugins.var]
# These are used by the postgres plugin
PGUSER = "postgres"
PGDATABASE = "telegram_parser"
POSTGRES_DB = "telegram_parser"
POSTGRES_USER = "postgres" 