[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
PORT = "8000"
WORKERS = "2"
PYTHONUNBUFFERED = "1"

# Additional Metadata for Railway Dashboard
[metadata]
name = "Telegram Parser API"
description = "FastAPI application for parsing Telegram groups"

[var]
DISABLE_DB = "false"
# Explicitly set the connection details
DATABASE_URL = "postgresql://postgres:${POSTGRES_PASSWORD}@postgresql.railway.app:5432/railway"

# This section defines your main application service
[service]
internal_port = 8080
auto_deploy = true

# Reference the PostgreSQL information for the main app
[[plugins]]
name = "PostgreSQL"
type = "postgresql"

# Reference the PostgreSQL variables in your main service
[plugins.var]
# These are used by the postgres plugin
POSTGRES_USER = "postgres"
POSTGRES_DB = "railway" 