[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[var]
DISABLE_DB = "false"
PORT = "8080"
# Explicitly set the connection details
DATABASE_URL = "postgresql://postgres:${POSTGRES_PASSWORD}@postgresql.railway.app:5432/railway"

# This section defines your main application service
[service]
internal_port = 8080
auto_deploy = true

# Reference the PostgreSQL information for the main app
[[plugins]]
name = "PostgreSQL"
type = "postgresql"

# Reference the PostgreSQL variables in your main service
[plugins.var]
# These are used by the postgres plugin
POSTGRES_USER = "postgres"
POSTGRES_DB = "railway" 