[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[var]
DISABLE_DB = "false"
PORT = "8080"

# Configure database connection - uncomment and adjust as needed
# DATABASE_URL = "${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"

[service]
internal_port = 8080
auto_deploy = true

[[services]]
name = "PostgreSQL"
auto_create = true
type = "postgres"

[services.var]
# These will be used by your application
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "auto_generated"
POSTGRES_DB = "telegram_parser" 