"""add channel posts and comments tables

Revision ID: 2fba9e2f9e5d
Revises: c75bfdd36d8b
Create Date: 2025-02-28 20:12:02.271333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fba9e2f9e5d'
down_revision = 'c75bfdd36d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 