"""add_parsing_progress_to_parsed_groups

Revision ID: 3e3357fc8f74
Revises: c8a9effa7fad
Create Date: 2025-03-03 22:04:01.029057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3357fc8f74'
down_revision = 'c8a9effa7fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_groups', sa.Column('parsing_progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_groups', 'parsing_progress')
    # ### end Alembic commands ### 