"""add is_premium to group member

Revision ID: 6c80b83cc3d8
Revises: 
Create Date: 2025-02-28 15:30:36.894072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c80b83cc3d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.alter_column('group_members', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.alter_column('parsed_groups', 'group_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('parsed_groups', 'group_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_parsed_groups_group_id'), 'parsed_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_parsed_groups_id'), 'parsed_groups', ['id'], unique=False)
    op.alter_column('telegram_tokens', 'api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('telegram_tokens', 'api_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_telegram_tokens_id'), 'telegram_tokens', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_telegram_tokens_id'), table_name='telegram_tokens')
    op.alter_column('telegram_tokens', 'api_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('telegram_tokens', 'api_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_parsed_groups_id'), table_name='parsed_groups')
    op.drop_index(op.f('ix_parsed_groups_group_id'), table_name='parsed_groups')
    op.alter_column('parsed_groups', 'group_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('parsed_groups', 'group_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.alter_column('group_members', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('group_members', 'is_premium')
    # ### end Alembic commands ### 