"""add is_channel field to parsed_groups

Revision ID: 910e84b54448
Revises: 2fba9e2f9e5d
Create Date: 2025-03-01 02:24:43.366503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910e84b54448'
down_revision = '2fba9e2f9e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_groups', sa.Column('is_channel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_groups', 'is_channel')
    # ### end Alembic commands ### 