"""Add default value for telegram_sessions updated_at

Revision ID: c8a9effa7fad
Revises: 910e84b54448
Create Date: 2025-03-03 17:09:32.177055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a9effa7fad'
down_revision = '910e84b54448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 